### ISSUE TITLE
plain password gets echoed back to console

### ISSUE THREAD

**Issue by PeterNerlich** [7HAL32/robolab-deploy#2]
Expected: When using the deploy script, the password does _not_ appear on the screen or gets geplaced with `*******`
Actual: the password promt echoes back the password as plain text.

Possible solution: http://stackoverflow.com/questions/9202224/getting-command-line-password-input-in-python

**Comment by lutzthies** [comment]
Thanks for the report. Your suggested solution is already being used since several commits before the public release. I can't reproduce the described behavior. As already explained in #3, it seems you are using an old version the was not intended for release. Make sure you have pulled the latest one. Please provide more detailed information if the problem persists.

**Comment by lutzthies** [comment]
We are preparing the rollout of a new release. Are there any updates on this issue? Otherwise I'll close it by the evening.
